%ifndef KEYBOARD_MAC
%define KEYBOARD_MAC

%define KEY.UP    0x48
%define KEY.DOWN  0x50
%define KEY.LEFT  0x4B
%define KEY.RIGHT 0x4D
%define KEY.ENTER 0x1C
%define KEY.UP.UP 0xc8
%define KEY.DOWN.UP 0xd0
%define KEY.LEFT.UP 0xcb
%define KEY.RIGHT.UP 0xcd
%define KEY.A 0x1e
%define KEY.S 0x1f
%define KEY.D 0x20
%define KEY.W 0x11
%define KEY.A.UP 0x9e
%define KEY.S.UP 0x9f
%define KEY.D.UP 0xa0
%define KEY.W.UP 0x91
%define KEY.SPACE 0x39

%endif ; KEYBOARD_MAC
